### ISSUE TITLE
Manual에서 ViewPager를 사용하는 것이 어떨까요?

### ISSUE THREAD

**Issue by WonJoongLee** [Mobeom/MoBeom#9]
<img src="https://user-images.githubusercontent.com/57510192/113496144-92935f80-9531-11eb-8edb-1d2c07544728.PNG" width="300" height="500"/>
<img src="https://user-images.githubusercontent.com/57510192/113496146-98894080-9531-11eb-8f16-957951f48b10.png" width="300" height="500"/>

기존 디자인에서 viewpager를 사용해서 아래처럼 바꾸는 것이 어떤가요?
아래 사진은 예시여서 참고만 해주시면 될 것 같아요.

**Comment by DongWooE** [comment]
나도 이 부분 동의함
